### ISSUE TITLE
修改MrGreed

### ISSUE THREAD

**Issue by lbyczzz** [Gongzhu-Society/MrIfOffline#6]
请问如何修改MrGreed为互相竞争、没有队友的？

**Comment by WhymustIhaveaname** [comment]
谢谢关注我们的仓库。

第一，`calc_relief` 只考虑自己的解脱，所以不用调整。 

第二，程序在 `clear_score` 函数中计算这一墩对自己的影响。在程序的 87、88 行(master 分支的)有这么一句话
```
        if winner%2==0:
            delta_score*=-1
```
它的意思是0和2赢的时候返回值乘一个负一(0123四个人排排座)。之后这个负一结合上所有调用 `clear_score` 处交错出现的正负一(152、171、186、261、273、287行)给出对自己成绩的估值。由此可以分析出程序的思路：`clear_score` 永远给出站在1、3号玩家(相对坐次)的得分，然后0、2号玩家再在调用函数时乘上负一。所以程序应当如此更改
1. 给 `clear_score` 增加一个参数，比如说叫 `curr_player` 表示为坐在这里的玩家考虑
2. 把 87、88 行改为
    ```
        if winner != curr_player:
            delta_score*=-1
    ```
3. 去掉调用 `clear_score` 前的正负一，并且把对的 `curr_player` 传入，比如 152 行 `as_last_player` 中的调用就应该改为
    ```
        score_temp=MrGreed.clear_score(four_cards_tmp,fmt_score_list,trick_start,scs_rmn_avg,3)\
                              +MrGreed.calc_relief(c,impc_dict,scs_rmn_avg,fmt_score_list[myplace][0])
    ```
   其实就在最后加了一个 3 因为最后一个玩家在相对坐次中是 3 (0123四个人排排座)。而 171 行 `as_third_player` 中的调用应该改为
    ```
        score_temp=MrGreed.clear_score(four_cards_tmp,fmt_score_list,trick_start,scs_rmn_avg,2)\
                              +MrGreed.calc_relief(c,impc_dict,scs_rmn_avg,fmt_score_list[myplace][0])
    ```
   注意 `curr_player` 的值从 3 变为了 2，调用时的负一也取消了。其他四处调用都这么改好应该就行了。

最早的程序 MrIf 是按自私写的，后来我们觉得这样不好，因为拱猪的趣味在于配合，所以后来写 MrGreed 时也就没考虑方便改成不带对家的问题，所以改写起来有些麻烦，为此我深表抱歉。另外，目前基于神经网络的 MrZeroTreeSimple 已经较为成熟，并且其实改这个程序会比改 Greed 更简单(但是需要重新训练神经网络)，您有空不妨一试。

如果您对我们的代码有疑问或者发现了不合理之处，我们非常欢迎您来 Issue 区讨论甚至直接提交 Pull Request！

P.S. 上面第二中编号 2 的更改 `delta_score*=-1` 意思是所有其他人的丢分就宛若自己的得分，但我觉得其他人的丢分还是不如自己的得分实在，所以不妨改为乘上一个 -1 到 0 之间的系数，比如 0.5 或 0.8：`delta_score*=-0.5`。

**Comment by lbyczzz** [comment]
非常感谢您！pick_a_card中的三处调用传的curr_player是什么呢？是当前出牌玩家的seat_id吗？代码我在刚熟悉阶段，另外您说的基于神经网络的MrZeroTreeSimple，我不是很熟悉这方面的知识，但会花时间去研究研究，再次非常感谢您的建议，对我帮助很大。

**Comment by WhymustIhaveaname** [comment]
261 行是 `if len(self.cards_on_table)==3` 时的情况，由于 `self.cards_on_table` 第一位是表示本墩谁先打的，所以此时已经出了两张牌，所以此时“我”是第三个打牌的，编号应当是 2。检查一下，`as_third_player` 中的 `clear_score` 前有 -1，261行也有 -1，所以应该没错。

之后的 273、287 行的编号应该是 1 和 0，同时不要忘记删除 `clear_score` 前的 -1。

祝您成功！

**Comment by lbyczzz** [comment]
您好，非常感谢您上次的指导，最近我在看MrZeroTreeSimple相关的代码，对这方面很是陌生，同时也在查找学习相关资料，不知能否指导下怎么让程序去训练呢？

**Comment by WhymustIhaveaname** [comment]
抱歉这么久才回复。与训练有关的代码在`MrZ_TB.py`中，`TB`的意思是`Trainer B`，因为最早的`MrZ_Trainer.py`是并行的，不利于理解，所以建议从`TB`开始看。

它的大致流程是，
* 在每个 epoch 中调用`prepare_data`使用当前版本的神经网络自己和自己玩收集一些训练数据
* 用收集到的训练数据训练几个 age，因为训练数据很宝贵（大部分时间都花在收集训练数据了），所以要多用几次，age 是比 epoch 小的时间单位。每个 epoch 有多少个 age 可以在 `train` 函数一开始的 `age_in_epoch` 里改
* 每隔一定的 epoch 就 benchmark 一下

具体的 benchmark 和 prepare data 的函数都是在 `MrZeroTreeSimple` 中定义的
`from MrZeroTreeSimple import benchmark,prepare_data`

**Comment by lbyczzz** [comment]
非常感谢您热心细致的指导，我会多花时间研究研究。再次谢谢您！

**Comment by lbyczzz** [comment]
您好，我成功使用cuda把MrZ_TB.py跑起来了，但我仍还是对模型的性能一无所知，请问您是怎么度量模型训练的优劣呢，另外如果是改成相互竞争、无配合的玩法是改MrZeroTreeSimple.py中的GameState下的reward吗？

**Comment by soundsinteresting** [comment]
我们采用和 MrGreed 对战的方式测试模型的性能。比方您有一个策略 X，想测试它究竟有多厉害，我们设计一个牌局，让两个机器人坐在南北，按照 X 打牌，另外两个 MrGreed 坐在东西。让他们打 1024 局牌(这个数您可以调)，然后总结两方的得分，算差。如果您运行 MrZ_TB.py，每次神经网络更新以后都会自动和 MrGreed 比试一下，重复上述计算，并打印出结果。

为什么我们要和 MrGreed 作比较？因为：
1. MrGreed 打牌很快，
2. 我们发现能够打赢 MrGreed 的分数这是对于策略的水平很好的度量，因为它对于很多策略具有传递性。您可以查看这篇总结[arxiv/2102.07495](https://arxiv.org/pdf/2102.07495.pdf) 的附录8.10。

是的。如果是相互竞争，您可以考虑改 MrZeroTreeSimple.py 的第78行为 `return scores[0]`，这个时候一个玩家只考虑自己的得分而不管队友。

**Comment by WhymustIhaveaname** [comment]
您能成功运行我们的程序是我们的荣幸！

在我们的[文章](https://arxiv.org/pdf/2102.07495.pdf)中的 Table 2 和 附录 8.10 论证了直接计算平均分差的传递性很好。
![image](https://user-images.githubusercontent.com/38423345/144699837-475a5808-cba8-494f-b307-fccbe4edcb6b.png)

具体而言 `MrZeroTreeSimple` 中有一个 `benchmark` 函数，每训练一段时间，`MrZ_TB` 就会将最新训练出的 AI 给这个函数由它测试 AI 的优劣。

**Comment by lbyczzz** [comment]
好的  谢谢您们！我目前一块GPU训练到160epoch，我用加载模型来预测出牌，发现出牌需要2-4秒，是我哪步不对吗，感觉这太慢了，有什么优化的方案吗，另外我最近发现有一个开源的斗地主的强化学习方案叫：douzero，推荐您们也可以看看，由于我目前水平有限，只明白一些片面的东西，我希望douzero能对你们有更大的启发，能做出更强的拱猪，我也能学习学习。

**Comment by WhymustIhaveaname** [comment]
两个重要的参数是生成 Scenario 的个数 BENCH_SMP_B 和 每个Scenario MCTS 的次数 mcts_k、mcts_b。每次出牌的时间是线型依赖于这两个参数的乘积的。如果每次生成 10 个 Scenario，每个 Scenario 进行大约 25 次 MCTS，在我们的 3070 上需要约 10 s。而实际 benchmark 时，为了节约时间，我们都是生成 5 个 Scenario，进行约 5 次 MCTS。经过实验我们发现，Scenario 数在 15 以下时，增加能提高水平，接近 15 或大于 15 时，运算时间会延长但是水平不会线性提升。MCTS 的次数是越大越强。

神经网络的求值和 MrGreed 这种 rule-based agent 比就是很慢，douzero 用一块 1080ti 一次实验也要跑两天，我们每次实验差不多是用 3070 跑 6 个小时。这也是我们用 MrGreed 做 baseline 的原因，它性能稳定，行为可靠，速度卓越。

douzero 文章发得很好，我们也在发表的第一时间就得知了。我本人打斗地主也不错，我也坚持观看学习天津卫视的旗开得胜斗地主节目，我发现斗地主的搜索树相对来说较浅，一局游戏结束所需要的轮数更少，而且每次出牌的选择也不多。这一点他们在文章中也提到了。

他们使用了一个 LSTM 来处理历史手牌，而我们目前也在研究如何从队友和对手的行为中推测他们的手牌，这是真正关键的、非完全信息博弈区别于 AlphaZero 的地方，我们在文章中做了一些尝试（MrZeroTree 比 MrZeroTreeSimple 多的就是这一部分），结果统计显著，确有提升，但是和人类高手仍有差距。

douzero 涉及到很专业的一些知识，我只能看懂皮毛，还是请 @soundsinteresting 和 @dashu233 两位理论大师来回答更多吧。

**Comment by lbyczzz** [comment]
真是谦虚了，看来这圈子很小。多谢您的回答，我还得多向各位学习。遇到问题再来向各位请教。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月4日(星期六) 下午3:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Gongzhu-Society/MrIfOffline] 修改MrGreed (#6)





 
两个重要的参数是生成 Scenario 的个数 BENCH_SMP_B 和 每个Scenario MCTS 的次数 mcts_k、mcts_b。每次出牌的时间是线型依赖于这两个参数的乘积的。如果每次生成 10 个 Scenario，每个 Scenario 进行大约 25 次 MCTS，在我们的 3070 上需要约 10 s。而实际 benchmark 时，为了节约时间，我们都是生成 5 个 Scenario，进行约 5 次 MCTS。经过实验我们发现，Scenario 数在 15 以下时，增加能提高水平，接近 15 或大于 15 时，运算时间会延长但是水平不会线性提升。MCTS 的次数是越大越强。
 
神经网络的求值和 MrGreed 这种 rule-based agent 比就是很慢，douzero 用一块 1080ti 一次实验也要跑两天，我们每次实验差不多是用 3070 跑 6 个小时。这也是我们用 MrGreed 做 baseline 的原因，它性能稳定，行为可靠，速度卓越。
 
douzero 文章发得很好，我们也在发表的第一时间就得知了。我本人打斗地主也不错，我也坚持观看学习天津卫视的旗开得胜斗地主节目，我发现斗地主的搜索树相对来说较浅，一局游戏结束所需要的轮数更少，而且每次出牌的选择也不多。这一点他们在文章中也提到了。
 
他们使用了一个 LSTM 来处理历史手牌，而我们目前也在研究如何从队友和对手的行为中推测他们的手牌，这是真正关键的、非完全信息博弈区别于 AlphaZero 的地方，我们在文章中做了一些尝试，但是提升不多。
 
douzero 涉及到很专业的一些知识，我只能看懂皮毛，还是请 @soundsinteresting 和 @dashu233 两位理论大师来回答更多吧。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
